spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easytrackingv3?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: easytrackingv3
    password: easytrackingv3
server:
  port: 6000
logging:
  file: easytracking.log
